--------------------------------------------------------
--  DDL for Sequence ROOM_ROOMID_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "GROUP6"."ROOM_ROOMID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

CREATE TABLE "GROUP6"."MEMBER" 
(	
    "MID" VARCHAR2(38 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"ACCOUNT" VARCHAR2(128 BYTE), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"IDENTITY" VARCHAR2(128 BYTE)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table ROOM
--------------------------------------------------------

CREATE TABLE "GROUP6"."ROOM" 
(	
    "MID" VARCHAR2(26 BYTE) NOT NULL , 
	"ROOMID" VARCHAR2(36 BYTE) NOT NULL , 
	"ROOMNAME" VARCHAR2(26 BYTE),
    "ROOMNUM" NUMBER(38,0),
    "INVALID" VARCHAR2(1 BYTE) DEFAULT 'Y',
    PRIMARY KEY(MID,ROOMID)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table ADDFRIEND
--------------------------------------------------------

CREATE TABLE "GROUP6"."ADDFRIEND" 
(	
    "MID" VARCHAR2(26 BYTE) NOT NULL, 
	"FRIENDID" VARCHAR2(26 BYTE) NOT NULL,
    PRIMARY KEY(MID,FRIENDID)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table ADDBLACK
--------------------------------------------------------

CREATE TABLE "GROUP6"."ADDBLACK" 
(	
    "MID" VARCHAR2(26 BYTE) NOT NULL, 
	"BLACKID" VARCHAR2(26 BYTE) NOT NULL,
    PRIMARY KEY(MID,BLACKID)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table JOINGAME
--------------------------------------------------------

CREATE TABLE "GROUP6"."JOINGAME" 
(	
    "MID" VARCHAR2(26 BYTE) NOT NULL, 
	"ROOMID" VARCHAR2(36 BYTE), 
    "JTIME" DATE, 
    PRIMARY KEY(MID)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table PLAY
--------------------------------------------------------

CREATE TABLE "GROUP6"."PLAY" 
(	
    "MID" VARCHAR2(26 BYTE) NOT NULL, 
	"ROOMID" VARCHAR2(36 BYTE) NOT NULL, 
    "GAMEID" VARCHAR2(26 BYTE) NOT NULL, 
    "STIME" DATE, 
    PRIMARY KEY(MID,ROOMID,GAMEID)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table GAME
--------------------------------------------------------

CREATE TABLE "GROUP6"."GAME" 
(	
    "GAMEID" VARCHAR2(26 BYTE) NOT NULL, 
	"GAMENAME" VARCHAR2(26 BYTE),
    "GAMEDESC" VARCHAR2(26 BYTE), 
    PRIMARY KEY(GAMEID)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table RECORD
--------------------------------------------------------

CREATE TABLE "GROUP6"."RECORD" 
(	
    "MID" VARCHAR2(26 BYTE) NOT NULL, 
	"ROOMID" VARCHAR2(36 BYTE) NOT NULL, 
    "GAMEID" VARCHAR2(26 BYTE) NOT NULL,
    "GAMETIME" NUMBER(38,0),
    "SCORE" NUMBER(38,0), 
    PRIMARY KEY(MID,ROOMID,GAMEID)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;